import React, { useEffect, useState } from 'react';
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, MapPin, Search, Sparkles, Users, X } from 'lucide-react';
import Dashboard, { StudentRegistrations } from './Dashboard.jsx';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const demoEvents = [
  { _id: '1', title: 'Design Thinking Sprint', description: 'Turn everyday problems into thoughtful solutions in this hands-on workshop.', category: 'Workshop', date: '2026-09-12T10:00:00', location: 'Innovation Lab', capacity: 40, registered: 24 },
  { _id: '2', title: 'Inter-college Hackathon', description: 'Build, learn and ship a useful idea with a team in one energetic weekend.', category: 'Technology', date: '2026-09-20T09:00:00', location: 'Main Auditorium', capacity: 100, registered: 67 },
  { _id: '3', title: 'Open Mic Evening', description: 'An easygoing evening for music, poetry and stories from our campus community.', category: 'Cultural', date: '2026-09-26T17:30:00', location: 'Amphitheatre', capacity: 80, registered: 51 }
];
const categories = ['All events', 'Workshop', 'Technology', 'Cultural', 'Sports'];
const formatDate = (value) => new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value));

export default function App() {
  const [events, setEvents] = useState(demoEvents); const [search, setSearch] = useState(''); const [category, setCategory] = useState('All events');
  const [selected, setSelected] = useState(null); const [joined, setJoined] = useState([]); const [notice, setNotice] = useState('');
  const [authMode, setAuthMode] = useState(null); const [authForm, setAuthForm] = useState({ name: '', email: '', password: '' }); const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('campusUser') || 'null')); const [authError, setAuthError] = useState(''); const [authLoading, setAuthLoading] = useState(false); const [showRegistrations, setShowRegistrations] = useState(false);
  useEffect(() => { fetch(`${API}/events`).then(r => r.ok ? r.json() : Promise.reject()).then(setEvents).catch(() => {}); }, []);
  useEffect(() => { if (user?.role !== 'student') { setJoined([]); return; } fetch(`${API}/registrations/mine`, { headers: { Authorization: `Bearer ${localStorage.getItem('campusToken')}` } }).then(response => response.ok ? response.json() : Promise.reject()).then(registrations => setJoined(registrations.filter(item => item.event?._id).map(item => item.event._id))).catch(() => {}); }, [user]);
  const filtered = events.filter(event => (category === 'All events' || event.category === category) && `${event.title} ${event.description} ${event.location}`.toLowerCase().includes(search.toLowerCase()));
  const authenticate = async (submitEvent) => { submitEvent.preventDefault(); setAuthError(''); setAuthLoading(true); try { const response = await fetch(`${API}/auth/${authMode}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(authForm) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Authentication failed.'); localStorage.setItem('campusToken', data.token); localStorage.setItem('campusUser', JSON.stringify(data.user)); setUser(data.user); setAuthMode(null); setAuthForm({ name: '', email: '', password: '' }); setNotice(`Welcome, ${data.user.name}.`); } catch (error) { setAuthError(error.message); } finally { setAuthLoading(false); } };
  const join = async (event) => { if (!user) { setSelected(null); setAuthMode('login'); setNotice('Sign in before registering for an event.'); return; } if (joined.includes(event._id)) { setNotice(`You are already registered for ${event.title}.`); return; } try { const response = await fetch(`${API}/registrations/${event._id}`, { method: 'POST', headers: { Authorization: `Bearer ${localStorage.getItem('campusToken')}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Registration failed.'); setJoined([...joined, event._id]); setNotice(`You are registered for ${event.title}.`); setSelected(null); } catch (error) { setNotice(error.message); } };
  return <div className="app-shell">
    <nav className="navbar navbar-expand-lg py-3"><div className="container"><a className="brand" href="#top"><span className="brand-mark"><Sparkles size={17}/></span>campus<span>events</span></a><div className="d-flex align-items-center gap-2"><span className="nav-link d-none d-md-inline">{user ? `Hi, ${user.name}` : 'Student portal'}</span>{user?.role === 'student' && <button className="btn btn-light btn-sm rounded-pill px-3" onClick={() => setShowRegistrations(true)}>My registrations</button>}{user?.role === 'admin' && <button className="btn btn-light btn-sm rounded-pill px-3" onClick={() => document.getElementById('admin-dashboard')?.scrollIntoView({ behavior: 'smooth' })}>Admin dashboard</button>}{user ? <button className="btn btn-outline-dark btn-sm rounded-pill px-3" onClick={() => { localStorage.removeItem('campusToken'); localStorage.removeItem('campusUser'); setUser(null); setShowRegistrations(false); }}>Log out</button> : <button className="btn btn-outline-dark btn-sm rounded-pill px-3" onClick={() => { setAuthError(''); setAuthMode('login'); }}>Log in</button>}</div></div></nav>
    {user?.role === 'admin' && <div id="admin-dashboard" className="container"><Dashboard token={localStorage.getItem('campusToken')} events={events} setEvents={setEvents} onNotice={setNotice}/></div>}
    <main id="top" className="container pb-5"><section className="intro"><div><p className="eyebrow"><span className="live-dot"/> CAMPUS, IN SESSION</p><h1>Make your<br/><em>next memory.</em></h1><p className="lede">Find the talks, workshops, showcases and little moments that make campus feel like home.</p></div><div className="intro-note"><span className="note-number">01</span><p>One calendar.<br/><strong>So many ways to show up.</strong></p></div></section>
      <section className="toolbar"><div className="search-wrap"><Search size={19}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search events, places, people..."/></div><div className="category-wrap"><select value={category} onChange={e => setCategory(e.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select><ChevronDown size={17}/></div></section>
      {notice && <div className="alert notice"><Check size={18}/> {notice}<button onClick={() => setNotice('')}><X size={16}/></button></div>}
      <section className="section-head"><div><span className="section-kicker">UP NEXT</span><h2>Events worth leaving<br className="d-md-none"/> your room for.</h2></div><span className="result-count">{filtered.length} events found</span></section>
      <section className="event-grid">{filtered.map((event, index) => <article className={`event-card card-${index % 3}`} key={event._id}><div className="card-top"><span className="category-label">{event.category}</span>{joined.includes(event._id) ? <span className="registered-badge"><Check size={12}/> Registered</span> : <span className="card-index">0{index + 1}</span>}</div><div className="event-date"><span>{new Date(event.date).toLocaleDateString('en-IN', { weekday: 'short' }).toUpperCase()}</span><strong>{new Date(event.date).getDate()}</strong><span>{new Date(event.date).toLocaleDateString('en-IN', { month: 'short' }).toUpperCase()}</span></div><h3>{event.title}</h3><p>{event.description}</p><div className="meta"><span><CalendarDays size={15}/> {formatDate(event.date)}</span><span><MapPin size={15}/> {event.location}</span></div><div className="card-footer"><span className="capacity"><Users size={15}/> {event.registered || 0} / {event.capacity} joined</span><button className={`arrow-btn ${joined.includes(event._id) ? 'registered-arrow' : ''}`} aria-label={`View ${event.title}`} onClick={() => setSelected(event)}><ArrowRight size={19}/></button></div></article>)}</section>
      {filtered.length === 0 && <div className="empty-state">No events match that search. Try another phrase.</div>}
      {user?.role === 'student' && showRegistrations && <StudentRegistrations token={localStorage.getItem('campusToken')} onNotice={setNotice} onRegistrationChange={eventId => setJoined(current => current.filter(id => id !== eventId))} onClose={() => setShowRegistrations(false)} onBrowse={() => { setShowRegistrations(false); document.getElementById('top')?.scrollIntoView({ behavior: 'smooth' }); }}/>}<section className="bottom-strip"><div><span className="section-kicker">YOUR CAMPUS, YOUR CALL</span><h2>Got a registration<br/><em>to manage?</em></h2></div><button className="text-button" onClick={() => user ? setShowRegistrations(!showRegistrations) : setAuthMode('login')}>{showRegistrations ? 'Hide my registrations' : 'View my registrations'} <ArrowRight size={18}/></button></section>
    </main>
    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="event-modal" onClick={e => e.stopPropagation()}><button className="close-btn" onClick={() => setSelected(null)}><X size={18}/></button><span className="category-label">{selected.category}</span><h2>{selected.title}</h2><p>{selected.description}</p><div className="modal-details"><span><CalendarDays size={17}/> {formatDate(selected.date)}</span><span><Clock3 size={17}/> {new Date(selected.date).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}</span><span><MapPin size={17}/> {selected.location}</span></div><button className={`btn w-100 py-3 ${joined.includes(selected._id) ? 'btn-success' : 'btn-dark'}`} disabled={joined.includes(selected._id)} onClick={() => join(selected)}>{joined.includes(selected._id) ? <><Check size={17}/> Already registered</> : <>Register for this event <ArrowRight size={17}/></>}</button></div></div>}
    {authMode && <div className="modal-backdrop" onClick={() => setAuthMode(null)}><form className="event-modal auth-modal" onSubmit={authenticate} onClick={e => e.stopPropagation()}><button type="button" className="close-btn" onClick={() => setAuthMode(null)}><X size={18}/></button><span className="category-label">{authMode === 'login' ? 'LOGIN' : 'STUDENT REGISTRATION'}</span><h2>{authMode === 'login' ? 'Welcome back.' : 'Join campus.'}</h2><p>{authMode === 'login' ? 'Students see registrations. Admins see the CRUD dashboard.' : 'New accounts are created as students.'}</p>{authMode === 'login' && <button type="button" className="demo-login" onClick={() => setAuthForm({ name: '', email: 'admin@campus.test', password: 'admin123' })}>Fill admin demo login</button>}{authMode === 'register' && <input required className="form-control" placeholder="Full name" value={authForm.name} onChange={e => setAuthForm({ ...authForm, name: e.target.value })}/>}<input required type="email" className="form-control" placeholder="Email address" value={authForm.email} onChange={e => setAuthForm({ ...authForm, email: e.target.value })}/><input required minLength="6" type="password" className="form-control" placeholder="Password (6+ characters)" value={authForm.password} onChange={e => setAuthForm({ ...authForm, password: e.target.value })}/>{authError && <div className="auth-error">{authError}</div>}<button className="btn btn-dark w-100 py-3" disabled={authLoading}>{authLoading ? 'Please wait...' : authMode === 'login' ? 'Log in' : 'Create student account'} <ArrowRight size={17}/></button><button type="button" className="switch-auth" onClick={() => { setAuthError(''); setAuthMode(authMode === 'login' ? 'register' : 'login'); }}>{authMode === 'login' ? 'Need a student account? Register' : 'Already registered? Log in'}</button></form></div>}
  </div>;
}
